### PR TITLE
#feature - Hover on link changes colour to brand orange.

### PR DESCRIPTION
**Pull request by Sehbaz**
This is my first contribution to LeicesterJS 🤗.

### CODE REVIEW

**Comment by danjordan** [comment]
Could you re-run `npm install` using npm v6.9.0 or remove the package-lock.json changes and then we'll merge.

Nice work, looks good 😎

**Comment by Sehbaz** [comment]
Great will do

**Comment by Sehbaz** [comment]
i have updated the package-lock.json file to original file code

**Comment by joshghent** [comment]
Looks good to me! Happy to merge @danjordan 👍

**Pull request merged**
